AbstractBotJob: Use write_changes instead of dry_run
internetarchive/openlibrary-client pull request #241
Opened 2021-07-01 05:41 UTC by cclauss

The default behavior of the `dry_run` parameter may be difficult to understand so this PR proposes to follow the examples of 2to3 and codespell and to instead use a more intuitive `-w, --write-changes` syntax.  Subclasses of AbstractBotJob and related tests may need to be modified.

This PR closes #(issue number)

## Description:

2021-07-01 11:38 UTC, jimman2003 requested changes
type should be store_true imo

2021-07-01 11:38 UTC, jimman2003 commented on olclient/bots.py
>              type=self._str2bool,
I want to remind you to use store_true as per our prev discussion #239

2021-08-18 08:39 UTC, jimman2003 commented
Is smth blocking this?

2021-08-24 15:26 UTC, jimman2003 commented
@cclauss is this done? seems complete to me..

2021-08-31 10:14 UTC, cclauss commented
Closing in favor of #255

2021-08-31 10:14 UTC, closed without merging